[CmdletBinding()]
param()

$ErrorActionPreference = "Stop"
$repoRoot = (Resolve-Path -LiteralPath (Split-Path -Parent $PSScriptRoot)).Path
$commonPath = Join-Path $repoRoot "Arcade-SegaSystem32.qsf"
$arabianPath = Join-Path $repoRoot "s32ArabianFight.qsf"

$profile = @(
    "",
    "# Arabian Fight dedicated revision.",
    "# Generated by tools/sync-arabianfight-qsf.ps1; edit the shared QSF above.",
    'set_global_assignment -name VERILOG_MACRO "S32_ARABFIGHT_ONLY=1"',
    'set_global_assignment -name VERILOG_MACRO "S32_V25_GAME_ONLY=1"',
    'set_global_assignment -name VERILOG_MACRO "S32_REAL_V25=1"',
    'set_global_assignment -name VERILOG_MACRO "S32_V60_NO_FP=1"',
    'set_global_assignment -name VERILOG_MACRO "S32_RELEASE_MINIMAL=1"',
    'set_global_assignment -name VERILOG_MACRO "S32_JT12_MLAB_SHIFTS=1"',
    'set_global_assignment -name VERILOG_MACRO "S32_V25_MLAB_FIFO=1"',
    'set_global_assignment -name VERILOG_MACRO "MISTER_DISABLE_SHADOWMASK=1"',
    ""
) -join [Environment]::NewLine

$crlf = [string][char]13 + [string][char]10
$lf = [string][char]10
$common = [IO.File]::ReadAllText($commonPath).Replace($crlf, $lf)
# The shared project can temporarily carry another dedicated game's macro
# while that profile is being developed. Never leak it into Arabian Fight's
# revision: the dedicated hardware contract below is the complete game set.
$common = (($common -split $lf) | Where-Object {
    $_ -notmatch 'VERILOG_MACRO\s+"S32_JPARK_ONLY=1"'
}) -join $lf
# Enforce the account-wide Quartus fast-build contract in the generated
# revision even if another profile temporarily changes the shared QSF.
$requiredAssignments = [ordered]@{
    'SAVE_DISK_SPACE'                        = 'OFF'
    'SMART_RECOMPILE'                        = 'ON'
    'FITTER_EFFORT'                          = '"FAST FIT"'
    'OPTIMIZATION_MODE'                      = '"HIGH PERFORMANCE EFFORT"'
    'OPTIMIZATION_TECHNIQUE'                 = 'SPEED'
    'ROUTER_TIMING_OPTIMIZATION_LEVEL'       = 'NORMAL'
    'PHYSICAL_SYNTHESIS_COMBO_LOGIC'         = 'OFF'
    'PHYSICAL_SYNTHESIS_COMBO_LOGIC_FOR_AREA'= 'OFF'
    'PHYSICAL_SYNTHESIS_REGISTER_DUPLICATION'= 'OFF'
    'SEED'                                   = '1'
    'NUM_PARALLEL_PROCESSORS'                = '6'
}
foreach ($assignment in $requiredAssignments.GetEnumerator()) {
    $pattern = '(?m)^set_global_assignment -name ' +
        [regex]::Escape($assignment.Key) + '\s+.*$'
    $replacement = 'set_global_assignment -name ' +
        $assignment.Key + ' ' + $assignment.Value
    if ($common -match $pattern) {
        $common = [regex]::Replace($common, $pattern, $replacement)
    }
    else {
        $common = $common.TrimEnd([char]13, [char]10) + $lf + $replacement + $lf
    }
}
$expected = $common.TrimEnd([char]13, [char]10) + $lf +
    $profile.Replace($crlf, $lf)
$current = if (Test-Path -LiteralPath $arabianPath -PathType Leaf) {
    [IO.File]::ReadAllText($arabianPath).Replace($crlf, $lf)
} else {
    ""
}

if ($current -cne $expected) {
    $temp = Join-Path $repoRoot ".s32ArabianFight.qsf.tmp.$PID.$([Guid]::NewGuid().ToString('N'))"
    $backup = Join-Path $repoRoot ".s32ArabianFight.qsf.backup.$PID.$([Guid]::NewGuid().ToString('N'))"
    try {
        [IO.File]::WriteAllText($temp, $expected, [Text.UTF8Encoding]::new($false))
        if (Test-Path -LiteralPath $arabianPath -PathType Leaf) {
            [IO.File]::Replace($temp, $arabianPath, $backup)
        }
        else {
            Move-Item -LiteralPath $temp -Destination $arabianPath
        }
        $verified = [IO.File]::ReadAllText($arabianPath).Replace($crlf, $lf)
        if ($verified -cne $expected) {
            throw "Atomic Arabian Fight QSF update did not verify byte-for-byte."
        }
    }
    finally {
        Remove-Item -LiteralPath $temp -Force -ErrorAction SilentlyContinue
        Remove-Item -LiteralPath $backup -Force -ErrorAction SilentlyContinue
    }
    Write-Host "Updated s32ArabianFight.qsf atomically from Arcade-SegaSystem32.qsf."
}
else {
    Write-Host "s32ArabianFight.qsf is current."
}
