[CmdletBinding()]
param()

$ErrorActionPreference = "Stop"
$repoRoot = (Resolve-Path -LiteralPath (Split-Path -Parent $PSScriptRoot)).Path
$commonPath = Join-Path $repoRoot "Arcade-SegaSystem32.qsf"
$alienPath = Join-Path $repoRoot "s32Alien3.qsf"

$profile = @(
    "",
    "# Alien 3: The Gun dedicated revision.",
    "# Generated by tools/sync-alien3-qsf.ps1; edit the shared QSF above.",
    '# The default programming-file path is deliberately uncompressed.',
    'set_global_assignment -name VERILOG_MACRO "S32_ALIEN3_ONLY=1"',
    'set_global_assignment -name VERILOG_MACRO "S32_V60_NO_FP=1"',
    'set_global_assignment -name VERILOG_MACRO "S32_RELEASE_MINIMAL=1"',
    'set_global_assignment -name VERILOG_MACRO "S32_JT12_MLAB_SHIFTS=1"',
    '# Alien 3 has ample post-pruning ALM headroom. Avoid sharing muxes on the',
    '# 96.6 MHz mixer/sprite paths and let synthesis optimize for speed.',
    'set_global_assignment -name AUTO_RESOURCE_SHARING OFF',
    ""
) -join [Environment]::NewLine

$crlf = [string][char]13 + [string][char]10
$lf = [string][char]10
$common = [IO.File]::ReadAllText($commonPath).Replace($crlf, $lf)

# A generated game revision must contain exactly its own dedicated macros.
$common = (($common -split $lf) | Where-Object {
    $_ -notmatch 'VERILOG_MACRO\s+"S32_(?:JPARK|ALIEN3|GOLDENAXE|GA2|ARABFIGHT|V25_GAME)_ONLY=1"' -and
    $_ -notmatch 'VERILOG_MACRO\s+"S32_REAL_V25=1"' -and
    $_ -notmatch 'VERILOG_MACRO\s+"S32_V25_MLAB_FIFO=1"'
}) -join $lf

# Enforce the account-wide Quartus build policy in the active revision while
# preserving all compilation databases for Smart Recompile.
$requiredAssignments = [ordered]@{
    'SAVE_DISK_SPACE'                         = 'OFF'
    'SMART_RECOMPILE'                         = 'ON'
    'FITTER_EFFORT'                           = '"FAST FIT"'
    'ROUTER_TIMING_OPTIMIZATION_LEVEL'        = 'NORMAL'
    'PHYSICAL_SYNTHESIS_COMBO_LOGIC'          = 'OFF'
    'PHYSICAL_SYNTHESIS_COMBO_LOGIC_FOR_AREA' = 'OFF'
    'PHYSICAL_SYNTHESIS_REGISTER_DUPLICATION' = 'OFF'
    'NUM_PARALLEL_PROCESSORS'                 = '6'
    'OPTIMIZATION_MODE'                       = 'BALANCED'
    'OPTIMIZATION_TECHNIQUE'                  = 'SPEED'
    'FITTER_AGGRESSIVE_ROUTABILITY_OPTIMIZATION' = 'AUTOMATICALLY'
    'ROUTER_LCELL_INSERTION_AND_LOGIC_DUPLICATION' = 'ON'
    'ALM_REGISTER_PACKING_EFFORT'             = 'LOW'
}
foreach ($assignment in $requiredAssignments.GetEnumerator()) {
    $pattern = '(?m)^set_global_assignment -name ' +
        [regex]::Escape($assignment.Key) + '\s+.*$'
    $replacement = 'set_global_assignment -name ' +
        $assignment.Key + ' ' + $assignment.Value
    if ($common -match $pattern) {
        $common = [regex]::Replace($common, $pattern, $replacement)
    }
    else {
        $common = $common.TrimEnd([char]13, [char]10) + $lf + $replacement + $lf
    }
}

$expected = $common.TrimEnd([char]13, [char]10) + $lf +
    $profile.Replace($crlf, $lf)
$current = if (Test-Path -LiteralPath $alienPath -PathType Leaf) {
    [IO.File]::ReadAllText($alienPath).Replace($crlf, $lf)
} else {
    ""
}

if ($current -cne $expected) {
    $temp = Join-Path $repoRoot ".s32Alien3.qsf.tmp.$PID.$([Guid]::NewGuid().ToString('N'))"
    $backup = Join-Path $repoRoot ".s32Alien3.qsf.backup.$PID.$([Guid]::NewGuid().ToString('N'))"
    try {
        [IO.File]::WriteAllText($temp, $expected, [Text.UTF8Encoding]::new($false))
        if (Test-Path -LiteralPath $alienPath -PathType Leaf) {
            [IO.File]::Replace($temp, $alienPath, $backup)
        }
        else {
            Move-Item -LiteralPath $temp -Destination $alienPath
        }
        $verified = [IO.File]::ReadAllText($alienPath).Replace($crlf, $lf)
        if ($verified -cne $expected) {
            throw "Atomic Alien 3 QSF update did not verify byte-for-byte."
        }
    }
    finally {
        Remove-Item -LiteralPath $temp -Force -ErrorAction SilentlyContinue
        Remove-Item -LiteralPath $backup -Force -ErrorAction SilentlyContinue
    }
    Write-Host "Updated s32Alien3.qsf atomically from Arcade-SegaSystem32.qsf."
}
else {
    Write-Host "s32Alien3.qsf is current."
}
