[CmdletBinding()]
param()

$ErrorActionPreference = "Stop"
$repoRoot = (Resolve-Path -LiteralPath (Split-Path -Parent $PSScriptRoot)).Path
$commonPath = Join-Path $repoRoot "Arcade-SegaSystem32.qsf"
$goldenAxePath = Join-Path $repoRoot "s32GoldenAxe.qsf"

$profile = @(
    "",
    "# Golden Axe: The Revenge of Death Adder dedicated revision.",
    "# Generated by tools/sync-goldenaxe-qsf.ps1; edit the shared QSF above.",
    'set_global_assignment -name VERILOG_MACRO "S32_GA2_ONLY=1"',
    'set_global_assignment -name VERILOG_MACRO "S32_GOLDENAXE_ONLY=1"',
    'set_global_assignment -name VERILOG_MACRO "S32_REAL_V25=1"',
    'set_global_assignment -name VERILOG_MACRO "S32_V60_NO_FP=1"',
    'set_global_assignment -name VERILOG_MACRO "S32_RELEASE_MINIMAL=1"',
    'set_global_assignment -name VERILOG_MACRO "S32_JT12_MLAB_SHIFTS=1"',
    'set_global_assignment -name VERILOG_MACRO "S32_V25_MLAB_FIFO=1"',
    ""
) -join [Environment]::NewLine

$crlf = [string][char]13 + [string][char]10
$lf = [string][char]10
$common = [IO.File]::ReadAllText($commonPath).Replace($crlf, $lf)
$expected = $common.TrimEnd([char]13, [char]10) + $lf +
    $profile.Replace($crlf, $lf)
$current = if (Test-Path -LiteralPath $goldenAxePath -PathType Leaf) {
    [IO.File]::ReadAllText($goldenAxePath).Replace($crlf, $lf)
} else {
    ""
}

if ($current -cne $expected) {
    $temp = Join-Path $repoRoot ".s32GoldenAxe.qsf.tmp.$PID.$([Guid]::NewGuid().ToString('N'))"
    $backup = Join-Path $repoRoot ".s32GoldenAxe.qsf.backup.$PID.$([Guid]::NewGuid().ToString('N'))"
    try {
        [IO.File]::WriteAllText($temp, $expected, [Text.UTF8Encoding]::new($false))
        if (Test-Path -LiteralPath $goldenAxePath -PathType Leaf) {
            [IO.File]::Replace($temp, $goldenAxePath, $backup)
        }
        else {
            Move-Item -LiteralPath $temp -Destination $goldenAxePath
        }
        $verified = [IO.File]::ReadAllText($goldenAxePath).Replace($crlf, $lf)
        if ($verified -cne $expected) {
            throw "Atomic Golden Axe QSF update did not verify byte-for-byte."
        }
    }
    finally {
        Remove-Item -LiteralPath $temp -Force -ErrorAction SilentlyContinue
        Remove-Item -LiteralPath $backup -Force -ErrorAction SilentlyContinue
    }
    Write-Host "Updated s32GoldenAxe.qsf atomically from Arcade-SegaSystem32.qsf."
}
else {
    Write-Host "s32GoldenAxe.qsf is current."
}
