// Simulation/behavioral placeholder for the Quartus fPLL IP.
// Real build: regenerate with the IP wizard (50 -> 96.648 / 48.324 MHz).
module pll (
    input  refclk_clk,
    input  reset_reset,
    output outclk0_clk,   // 96.648 MHz
    output outclk1_clk,   // 48.324 MHz
    output outclk2_clk,   // 96.648 MHz, 180 deg (SDRAM_CLK)
    output locked_export
);
`ifdef SIMULATION
reg c0 = 0, c1 = 0;
always #5.17 c0 = ~c0;
always #10.34 c1 = ~c1;
assign outclk0_clk = c0;
assign outclk1_clk = c1;
assign outclk2_clk = c0;
assign locked_export = 1'b1;
`else
// Hardware builds include synthesis/pll.qip, generated by tools/build.bat.
// These assignments keep standalone lint possible but are never release RTL.
assign outclk0_clk = refclk_clk;
assign outclk1_clk = refclk_clk;
assign outclk2_clk = refclk_clk;
assign locked_export = ~reset_reset;
`endif
endmodule
